version: '2'
services:
 transmission:
  secrets:
    - openvpn_creds
  image: haugene/transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "9091:9091"
    # - "8888:8888" # proxy support
  volumes:
    - ${DATA_VOLUME}:/data # where transmission will store the data
    - ${CONFIG_VOLUME}:/config # where transmission-home is stored
    - ${CUSTOM_VOLUME}:/etc/openvpn/custom # custom openvpn config
  environment:
    - OPENVPN_PROVIDER=custom
    - OPENVPN_CONFIG=${VPN_CONFIG}
    - LOCAL_NETWORK=${LCL_NETWORK}
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
secrets:
  openvpn_creds:
    file: ${CREDS_FILE}
 # proxy:
 #  image: haugene/transmission-openvpn-proxy
 #  links:
 #    - transmission
 #  ports:
 #    - 8080:8080
 #  volumes:
 #    - /etc/localtime:/etc/localtime:ro

 # rss:
 #  image: haugene/transmission-rss
 #  links:
 #    - transmission
 #  environment:
 #    - RSS_URL=http://.../xxxxx.rss
